
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PrivateVotingContractArtifactJson from '../target/private_voting-PrivateVoting.json' with { type: 'json' };
export const PrivateVotingContractArtifact = loadContractArtifact(PrivateVotingContractArtifactJson as NoirCompiledContract);


      export type Vote = {
        election_id: FieldLike
candidate: FieldLike
voter: AztecAddressLike
      }
    

      export type TallyUpdated = {
        election_id: FieldLike
candidate: FieldLike
tally: FieldLike
      }
    

/**
 * Type-safe interface for contract PrivateVoting;
 */
export class PrivateVotingContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PrivateVotingContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PrivateVotingContract {
    return Contract.at(address, PrivateVotingContract.artifact, wallet) as PrivateVotingContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PrivateVotingContract>(
      wallet,
      {
        artifact: PrivateVotingContractArtifact,
        postDeployCtor: (instance, wallet) => PrivateVotingContract.at(instance.address, wallet),
        args: [admin],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PrivateVotingContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<PrivateVotingContract['methods'][M]>
  ) {
    return DeployMethod.create<PrivateVotingContract>(
      opts.wallet,
      {
        artifact: PrivateVotingContractArtifact,
        postDeployCtor: (instance, wallet) => PrivateVotingContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PrivateVotingContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PrivateVotingContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'tally' | 'vote_ended' | 'active_at_block' | 'vote_claims'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
tally: {
      slot: new Fr(2n),
    },
vote_ended: {
      slot: new Fr(3n),
    },
active_at_block: {
      slot: new Fr(4n),
    },
vote_claims: {
      slot: new Fr(5n),
    }
      } as ContractStorageLayout<'admin' | 'tally' | 'vote_ended' | 'active_at_block' | 'vote_claims'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** cast_vote(election_id: struct, candidate: field) */
    cast_vote: ((election_id: { id: FieldLike }, candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** end_vote(election_id: struct) */
    end_vote: ((election_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_tally(election_id: struct, candidate: field) */
    get_tally: ((election_id: { id: FieldLike }, candidate: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** start_vote(election_id: struct) */
    start_vote: ((election_id: { id: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { Vote: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, TallyUpdated: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      Vote: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "election_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "candidate",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "voter",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "PrivateVoting::Vote"
},
        eventSelector: EventSelector.fromString("0xb5382344"),
        fieldNames: ["election_id","candidate","voter"],
      },
TallyUpdated: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "election_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "candidate",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "tally",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "PrivateVoting::TallyUpdated"
},
        eventSelector: EventSelector.fromString("0xedc1077e"),
        fieldNames: ["election_id","candidate","tally"],
      }
    };
  }
  
}
